<?xml version="1.0" encoding="utf-8"?><Database Name="StaticVoid.OrmPerformance.Harness.EntityFramework4_1.TestContext" Class="TestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=StaticVoid.OrmPerformance.Harness.EntityFramework4_1.TestContext;Integrated Security=True" SettingsObjectName="StaticVoid.OrmPerformance.Harness.Linq2Sql.Properties.Settings" SettingsPropertyName="StaticVoid_OrmPerformance_Harness_EntityFramework4_1_TestContextConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TestEntities" Member="TestEntities">
    <Type Name="TestEntity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="TestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="TestInt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
    </Type>
  </Table>
</Database>